#!/usr/bin/perl -w

# Convert mp3 data to 16-bit, backward-endian table data for PIC18 devices.
# NOTE: mp3 data should have an even number of bytes! Otherwise, one garbage byte will be stored at the end of the table as padding...
# This is for built-into-PIC test data only; actual mp3 data/frames sent from the external device won't have this restriction.

$tablename="rand";



open OUTFILE, "> $tablename.inc" or die "Couldn't open OUTFILE: $!\n";

$count = 0;

printf OUTFILE "; \$Id: \$\n\n; Random colors table generated by rand.pl\n\n";

printf OUTFILE "$tablename:\n";

while ($count<128) 
{
	$one=(rand()*3);
	$two=(rand()*3);

	$one=$one*$one;
	$two=$two*$two;

	printf OUTFILE ("\tDW H'%02X%02X'\n", $two, $one);
	printf ("\tDW H'%02X%02X'\n", ord($two), ord($one));
	$count++;
}

print "Total $count lines ";
print OUTFILE "\n; Total $count lines\n";

$count = $count * 2;
print " ($count bytes)\n";
print OUTFILE "; ($count bytes)\n";

close(OUTFILE);
